### GET ALL 
### Obtener todas los items
GET http://localhost:3000/api/items

### GET ONE
### Obtener un item
GET http://localhost:3000/api/items/{{id}}

### POST
### Crear un nuevo item
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Espada",
    "description": "Arma blanca, filosa y peligrosa."
}

### POST2
# @name createItem
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Arco",
    "description": "Arma de proyectil liviana y ofensiva."
}

### POST ITEM TO UPDATE
# @name createItemToUpdate
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Flechas",
    "description": "Accesorio que da lugar al uso del arco."
}

### POST ITEM TO DELETE
# @name createItemToDelete
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Tijera",
    "description": "Herramienta utilizada con el objetivo de matar."
}

### PUT
### Modificar un item
PUT http://localhost:3000/api/items/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Flechas",
    "description": "Accesorio de punta filosa que da lugar al uso del arco."
}

### DELETE
### Borrar un item
DELETE http://localhost:3000/api/items/{{idToDelete}}

### IDs
@id = {{createItem.response.body.data.id}}
@idToUpdate = {{createItemToUpdate.response.body.data.id}}
@idToDelete = {{createItemToDelete.response.body.data.id}}