### GET ALL 
### Obtener todas las categorías
GET http://localhost:3000/api/categories

### GET ONE
### Obtener una categoría
GET http://localhost:3000/api/categories/{{id}}

### POST
### Crear una nueva categoría
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Lácteos",
    "description": "Productos derivados de la leche como yogures, quesos y manteca."
}

### POST2
# @name createCategory
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Carnicería",
    "description": "Carnes bovina y ovina, pollos y otras alternativas."
}

### POST CATEGORY TO UPDATE
# @name createCategoryToUpdate
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Frutas",
    "description": "Partes de las plantas fundamentales para la nutrición."
}

### POST CATEGORY TO DELETE
# @name createCategoryToDelete
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Postres",
    "description": "Alimento dulce servido como final de una comida."
}

### PUT
### Modificar una categoría
PUT http://localhost:3000/api/categories/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Frutas y Verduras",
    "description": "Partes comestibles de las plantas fundamentales para la nutrición."
}

### DELETE
### Borrar una categoría
DELETE http://localhost:3000/api/categories/{{idToDelete}}

### IDs
@id = {{createCategory.response.body.data.id}}
@idToUpdate = {{createCategoryToUpdate.response.body.data.id}}
@idToDelete = {{createCategoryToDelete.response.body.data.id}}