### GET ALL 
### Obtener todos los productos
GET http://localhost:3000/api/products

### GET ONE
### Obtener un producto
GET http://localhost:3000/api/products/{{id}}

### POST
### Crear un nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Leche Descremada La Serenísima",
    "description": "Leche descremada pasteurizada, rica en calcio y proteínas.",
    "price": 850.50,
    "stock": 100,
    "category": 1,
    "tags": [1, 2]
}

### POST2
# @name createProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Pan Integral Bimbo",
    "description": "Pan integral con semillas, rico en fibra y nutrientes.",
    "price": 1200.00,
    "stock": 150,
    "category": 2,
    "tags": [3]
}

### POST PRODUCT TO UPDATE
# @name createProductToUpdate
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Detergente Ala",
    "description": "Detergente líquido para ropa, concentrado.",
    "price": 2500.75,
    "stock": 100,
    "category": 3,
    "tags": []
}

### POST PRODUCT TO DELETE
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Coca Cola 1.5L",
    "description": "Bebida gaseosa cola, botella de 1.5 litros.",
    "price": 1800.00,
    "stock": 200,
    "category": 3,
    "tags": []
}

### PUT
### Modificar un producto
PUT http://localhost:3000/api/products/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Detergente Ala Concentrado",
    "description": "Detergente líquido para ropa, fórmula concentrada que rinde más y limpia mejor.",
    "price": 2750.00,
    "stock": 120,
    "category": 3,
    "tags": [3]
}

### DELETE
### Borrar un producto
DELETE http://localhost:3000/api/products/{{idToDelete}}

### IDs
@id = {{createProduct.response.body.data.id}}
@idToUpdate = {{createProductToUpdate.response.body.data.id}}
@idToDelete = {{createProductToDelete.response.body.data.id}}