### GET ALL 
### Obtener todos los productos
GET http://localhost:3000/api/products

### GET ONE
### Obtener un producto
GET http://localhost:3000/api/products/{{id}}

### POST
### Crear un nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Leche Entera La Serenísima",
    "description": "Leche entera pasteurizada, rica en calcio y proteínas.",
    "price": 2350.50,
    "stock": 100,
    "category": 1,
    "tags": [1]
}

### POST2
# @name createProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Manzanas Verdes 1kg",
    "description": "Fruta del manzano común.",
    "price": 2890,
    "stock": 150,
    "category": 3,
    "tags": [2, 3, 4]
}

### POST PRODUCT TO UPDATE
# @name createProductToUpdate
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Vacío 1kg",
    "description": "Corte de carne bovina proveniente de la zona del abdomen.",
    "price": 12650.75,
    "stock": 20,
    "category": 2,
    "tags": [1, 4]
}

### POST PRODUCT TO DELETE
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Castañas De Cajú Natfood 80g",
    "description": "Semillas del fruto del árbol de cajú.",
    "price": 2999.99,
    "stock": 200,
    "category": 3,
    "tags": [2, 3, 4]
}

### PUT
### Modificar un producto
PUT http://localhost:3000/api/products/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Vacío de Novillo 1kg",
    "description": "Corte de carne bovina proveniente de la zona del abdomen.",
    "price": 13450,
    "stock": 12,
    "category": 2,
    "tags": [1, 4]
}

### DELETE
### Borrar un producto
DELETE http://localhost:3000/api/products/{{idToDelete}}

### IDs
@id = {{createProduct.response.body.data.id}}
@idToUpdate = {{createProductToUpdate.response.body.data.id}}
@idToDelete = {{createProductToDelete.response.body.data.id}}